version: "3.9"
services:
  webapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash django-start.sh
  db:
    image: postgres:15.2-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  dbdata:
